# Starter Makefile (adapt to your backend stack)

.PHONY: fmt lint test

fmt:
	@echo "Add formatter commands here (black/ruff/prettier/etc.)"

lint:
	@echo "Add linter commands here"

test:
	@echo "Add unit + contract tests here"

dev:
	@echo "Start your backend here (docker compose + server)"
