const DISPLAY_CAPABILITIES_OFF = {
  session: false,
  camera: false,
  photoCapture: false,
  videoStream: false,
  audio: false,
  display: false,
  displayVideo: false,
};

const DISPLAY_CAPABILITIES_READY = {
  session: true,
  camera: true,
  photoCapture: true,
  videoStream: true,
  audio: true,
  display: true,
  displayVideo: true,
};

const FIXTURE_DEVICE = {
  deviceId: 'AA:BB:CC:DD',
  deviceName: 'Meta Ray-Ban Display',
  source: 'bonded+scan',
  rssi: -41,
};

export const DAT_DISPLAY_STATES = {
  unavailable: {
    id: 'dat-unavailable',
    platform: 'unknown',
    available: false,
    sdkLinked: false,
    sdkConfigured: false,
    integrationMode: 'unavailable',
    capabilities: DISPLAY_CAPABILITIES_OFF,
    sessionState: 'unavailable',
    targetConnectionState: 'unselected',
    displayConnectionState: 'unavailable',
    displayReady: false,
    displayDamRequired: true,
    displayDamEnabled: false,
    datAppModelEnabled: false,
    configWarnings: ['DAT native module is unavailable in this build.'],
    fallback: {
      reason: 'dat_native_display_unavailable',
      renderPath: 'mobile-card',
      message: 'Display unavailable. Showing content on phone.',
    },
  },
  disabled: {
    id: 'dat-disabled',
    platform: 'android',
    available: true,
    sdkLinked: true,
    sdkConfigured: false,
    integrationMode: 'reference_only',
    capabilities: {
      ...DISPLAY_CAPABILITIES_OFF,
      session: true,
      audio: true,
    },
    sessionState: 'idle',
    targetConnectionState: 'selected',
    displayConnectionState: 'disabled',
    displayReady: false,
    displayDamRequired: true,
    displayDamEnabled: false,
    datAppModelEnabled: false,
    selectedDeviceId: FIXTURE_DEVICE.deviceId,
    selectedDeviceName: FIXTURE_DEVICE.deviceName,
    configWarnings: ['DAT display access is disabled for this build.'],
    fallback: {
      reason: 'dat_native_display_unavailable',
      renderPath: 'display-webapp',
      message: 'Native display access is disabled. Opening display webapp preview.',
    },
  },
  unsupported: {
    id: 'display-unsupported',
    platform: 'android',
    available: true,
    sdkLinked: true,
    sdkConfigured: true,
    integrationMode: 'sdk_reflection',
    capabilities: {
      ...DISPLAY_CAPABILITIES_READY,
      display: false,
      displayVideo: false,
    },
    sessionState: 'ready',
    targetConnectionState: 'connected',
    displayConnectionState: 'unsupported',
    displayReady: false,
    displayDamRequired: true,
    displayDamEnabled: true,
    datAppModelEnabled: true,
    selectedDeviceId: '11:22:33:44',
    selectedDeviceName: 'Ray-Ban Meta',
    fallback: {
      reason: 'display_unsupported',
      renderPath: 'audio-summary',
      message: 'Connected glasses do not advertise display capability.',
    },
  },
  firmwareUpdateRequired: {
    id: 'firmware-update-required',
    platform: 'android',
    available: true,
    sdkLinked: true,
    sdkConfigured: true,
    integrationMode: 'sdk_reflection',
    capabilities: {
      ...DISPLAY_CAPABILITIES_READY,
      display: false,
      displayVideo: false,
    },
    sessionState: 'blocked',
    registrationState: 'available',
    targetConnectionState: 'connected',
    displayConnectionState: 'firmware_update_required',
    displayReady: false,
    displayDamRequired: true,
    displayDamEnabled: true,
    datAppModelEnabled: true,
    selectedDeviceId: FIXTURE_DEVICE.deviceId,
    selectedDeviceName: FIXTURE_DEVICE.deviceName,
    targetLastSeenAt: 1779440400000,
    targetRssi: FIXTURE_DEVICE.rssi,
    requiredAction: 'open_firmware_update',
    displayLastAction: 'render_display_widget',
    displayLastStatus: 'firmware_update_required',
    displayLastError: 'firmware_update_required',
    displayLifecycleStages: ['target_selected'],
    configWarnings: ['Glasses firmware update is required before DAT display rendering.'],
    fallback: {
      reason: 'firmware_update_required',
      renderPath: 'mobile-card',
      message: 'Glasses firmware update is required before DAT display rendering.',
      requiredAction: 'open_firmware_update',
    },
  },
  datAppUpdateRequired: {
    id: 'dat-app-update-required',
    platform: 'android',
    available: true,
    sdkLinked: true,
    sdkConfigured: true,
    integrationMode: 'sdk_reflection',
    capabilities: {
      ...DISPLAY_CAPABILITIES_READY,
      display: false,
      displayVideo: false,
    },
    sessionState: 'blocked',
    registrationState: 'available',
    targetConnectionState: 'connected',
    displayConnectionState: 'dat_app_update_required',
    displayReady: false,
    displayDamRequired: true,
    displayDamEnabled: true,
    datAppModelEnabled: false,
    selectedDeviceId: FIXTURE_DEVICE.deviceId,
    selectedDeviceName: FIXTURE_DEVICE.deviceName,
    targetLastSeenAt: 1779440400000,
    targetRssi: FIXTURE_DEVICE.rssi,
    requiredAction: 'open_dat_glasses_app_update',
    displayLastAction: 'render_display_widget',
    displayLastStatus: 'dat_app_update_required',
    displayLastError: 'dat_app_update_required',
    displayLifecycleStages: ['target_selected', 'session_start_failed'],
    configWarnings: ['DAT glasses app update is required before display rendering.'],
    fallback: {
      reason: 'dat_app_update_required',
      renderPath: 'mobile-card',
      message: 'DAT glasses app update is required before display rendering.',
      requiredAction: 'open_dat_glasses_app_update',
    },
  },
  lifecycleError: {
    id: 'display-lifecycle-error',
    platform: 'android',
    available: true,
    sdkLinked: true,
    sdkConfigured: true,
    integrationMode: 'sdk_reflection',
    capabilities: DISPLAY_CAPABILITIES_READY,
    sessionState: 'started',
    registrationState: 'available',
    targetConnectionState: 'connected',
    displayConnectionState: 'error',
    displayReady: false,
    displayDamRequired: true,
    displayDamEnabled: true,
    datAppModelEnabled: true,
    selectedDeviceId: FIXTURE_DEVICE.deviceId,
    selectedDeviceName: FIXTURE_DEVICE.deviceName,
    targetLastSeenAt: 1779440400000,
    targetRssi: FIXTURE_DEVICE.rssi,
    requiredAction: null,
    displayLastAction: 'render_display_widget',
    displayLastStatus: 'error',
    displayLastError: 'display_lifecycle_error',
    displayLifecycleStages: ['target_selected', 'session_started', 'display_starting'],
    configWarnings: ['Display lifecycle failed before content could be sent.'],
    fallback: {
      reason: 'display_lifecycle_error',
      renderPath: 'mobile-card',
      message: 'Display lifecycle failed before content could be sent.',
      requiredAction: null,
    },
  },
  ready: {
    id: 'display-ready',
    platform: 'android',
    available: true,
    sdkLinked: true,
    sdkConfigured: true,
    integrationMode: 'sdk_reflection',
    capabilities: DISPLAY_CAPABILITIES_READY,
    sessionState: 'ready',
    registrationState: 'available',
    targetConnectionState: 'ready',
    displayConnectionState: 'ready',
    displayReady: true,
    displayDamRequired: true,
    displayDamEnabled: true,
    datAppModelEnabled: true,
    selectedDeviceId: FIXTURE_DEVICE.deviceId,
    selectedDeviceName: FIXTURE_DEVICE.deviceName,
    targetLastSeenAt: 1779440400000,
    targetRssi: FIXTURE_DEVICE.rssi,
    displayLastAction: 'render_display_widget',
    displayLastStatus: 'ready',
    displayLastUpdatedAt: 1779440401000,
    fallback: null,
  },
};

export const ANDROID_DISPLAY_ACCESS_LIFECYCLE_STATES = [
  {
    id: 'android-idle',
    sourceSample: 'external/meta-wearables-dat-android/samples/DisplayAccess',
    stage: 'idle',
    connectionState: 'DISCONNECTED',
    deviceSessionState: null,
    displayState: null,
    selectedDeviceId: null,
    isSessionActive: false,
    isDisplayAttached: false,
    isStartingSession: false,
    isPreparingDisplay: false,
    snackbarMessage: null,
    canRenderDisplay: false,
  },
  {
    id: 'android-starting-session',
    sourceSample: 'external/meta-wearables-dat-android/samples/DisplayAccess',
    stage: 'starting_session',
    nativeCall: 'Wearables.createSession(SpecificDeviceSelector(deviceId))',
    connectionState: 'CONNECTING',
    deviceSessionState: 'STARTING',
    displayState: null,
    selectedDeviceId: FIXTURE_DEVICE.deviceId,
    isSessionActive: false,
    isDisplayAttached: false,
    isStartingSession: true,
    isPreparingDisplay: true,
    snackbarMessage: 'Starting session...',
    canRenderDisplay: false,
  },
  {
    id: 'android-session-started',
    sourceSample: 'external/meta-wearables-dat-android/samples/DisplayAccess',
    stage: 'session_started',
    nativeEvent: 'DeviceSessionState.STARTED',
    connectionState: 'CONNECTED',
    deviceSessionState: 'STARTED',
    displayState: null,
    selectedDeviceId: FIXTURE_DEVICE.deviceId,
    isSessionActive: true,
    isDisplayAttached: false,
    isStartingSession: false,
    isPreparingDisplay: true,
    snackbarMessage: 'Session started',
    canRenderDisplay: false,
  },
  {
    id: 'android-attaching-display',
    sourceSample: 'external/meta-wearables-dat-android/samples/DisplayAccess',
    stage: 'attaching_display',
    nativeCall: 'DeviceSession.addDisplay()',
    connectionState: 'CONNECTED',
    deviceSessionState: 'STARTED',
    displayState: null,
    selectedDeviceId: FIXTURE_DEVICE.deviceId,
    isSessionActive: true,
    isDisplayAttached: false,
    isStartingSession: false,
    isPreparingDisplay: true,
    snackbarMessage: 'Attaching display...',
    canRenderDisplay: false,
  },
  {
    id: 'android-display-attached',
    sourceSample: 'external/meta-wearables-dat-android/samples/DisplayAccess',
    stage: 'display_attached',
    nativeEvent: 'Display attached',
    connectionState: 'CONNECTED',
    deviceSessionState: 'STARTED',
    displayState: null,
    selectedDeviceId: FIXTURE_DEVICE.deviceId,
    isSessionActive: true,
    isDisplayAttached: true,
    isStartingSession: false,
    isPreparingDisplay: true,
    snackbarMessage: 'Display attached',
    canRenderDisplay: false,
  },
  {
    id: 'android-display-starting',
    sourceSample: 'external/meta-wearables-dat-android/samples/DisplayAccess',
    stage: 'display_starting',
    nativeEvent: 'DisplayState.STARTING',
    connectionState: 'CONNECTED',
    deviceSessionState: 'STARTED',
    displayState: 'STARTING',
    selectedDeviceId: FIXTURE_DEVICE.deviceId,
    isSessionActive: true,
    isDisplayAttached: true,
    isStartingSession: false,
    isPreparingDisplay: true,
    snackbarMessage: 'Display attached',
    canRenderDisplay: false,
  },
  {
    id: 'android-display-ready',
    sourceSample: 'external/meta-wearables-dat-android/samples/DisplayAccess',
    stage: 'display_ready',
    nativeEvent: 'DisplayState.STARTED',
    connectionState: 'CONNECTED',
    deviceSessionState: 'STARTED',
    displayState: 'STARTED',
    selectedDeviceId: FIXTURE_DEVICE.deviceId,
    isSessionActive: true,
    isDisplayAttached: true,
    isStartingSession: false,
    isPreparingDisplay: false,
    snackbarMessage: 'Display ready',
    canRenderDisplay: true,
  },
  {
    id: 'android-content-sent',
    sourceSample: 'external/meta-wearables-dat-android/samples/DisplayAccess',
    stage: 'content_sent',
    nativeCall: 'Display.sendContent(content)',
    connectionState: 'CONNECTED',
    deviceSessionState: 'STARTED',
    displayState: 'STARTED',
    selectedDeviceId: FIXTURE_DEVICE.deviceId,
    isSessionActive: true,
    isDisplayAttached: true,
    isStartingSession: false,
    isPreparingDisplay: false,
    snackbarMessage: 'Content sent',
    displayLastAction: 'render_display_widget',
    displayLastStatus: 'sent',
    canRenderDisplay: true,
  },
  {
    id: 'android-display-stopped',
    sourceSample: 'external/meta-wearables-dat-android/samples/DisplayAccess',
    stage: 'display_stopped',
    nativeEvent: 'DisplayState.STOPPED',
    connectionState: 'DISCONNECTED',
    deviceSessionState: 'STOPPED',
    displayState: 'STOPPED',
    selectedDeviceId: null,
    isSessionActive: false,
    isDisplayAttached: false,
    isStartingSession: false,
    isPreparingDisplay: false,
    snackbarMessage: 'Display session stopped',
    canRenderDisplay: false,
  },
];

export const IOS_DISPLAY_FALLBACK_STATES = {
  registrationUnavailable: {
    id: 'ios-registration-unavailable',
    sourceSample: 'external/meta-wearables-dat-ios/samples/DisplayAccess',
    platform: 'ios',
    registrationState: 'unavailable',
    isConnected: false,
    isSending: false,
    didFailToStartSession: false,
    requiresDATAppUpdate: false,
    errorMessage: null,
    fallback: {
      reason: 'dat_native_display_unavailable',
      renderPath: 'mobile-card',
      message: 'DAT registration is unavailable. Showing display content on phone.',
    },
  },
  datAppUpdateRequired: {
    id: 'ios-dat-app-update-required',
    sourceSample: 'external/meta-wearables-dat-ios/samples/DisplayAccess',
    platform: 'ios',
    registrationState: 'available',
    isConnected: false,
    isSending: false,
    didFailToStartSession: true,
    requiresDATAppUpdate: true,
    errorName: 'DeviceSessionError.datAppOnTheGlassesUpdateRequired',
    errorMessage: 'DAT app on the glasses update required.',
    fallback: {
      reason: 'display_unsupported',
      renderPath: 'notification',
      message: 'Update the glasses DAT app before using native display.',
    },
  },
  displayStartFailed: {
    id: 'ios-display-start-failed',
    sourceSample: 'external/meta-wearables-dat-ios/samples/DisplayAccess',
    platform: 'ios',
    registrationState: 'available',
    isConnected: false,
    isSending: false,
    didFailToStartSession: true,
    requiresDATAppUpdate: false,
    errorMessage: 'Failed to start display: Display capability unavailable.',
    fallback: {
      reason: 'dat_native_display_unavailable',
      renderPath: 'simulator',
      message: 'Native display failed to start. Showing simulator preview.',
    },
  },
  pendingActionQueued: {
    id: 'ios-pending-action-queued',
    sourceSample: 'external/meta-wearables-dat-ios/samples/DisplayAccess',
    platform: 'ios',
    registrationState: 'available',
    isConnected: false,
    isSending: false,
    didFailToStartSession: false,
    requiresDATAppUpdate: false,
    pendingActionQueued: true,
    displayState: 'starting',
    fallback: {
      reason: 'session_not_ready',
      renderPath: 'mobile-card',
      message: 'Display session is preparing. Keeping the mobile card visible.',
    },
  },
  fallbackReady: {
    id: 'ios-fallback-ready',
    sourceSample: 'external/meta-wearables-dat-ios/samples/DisplayAccess',
    platform: 'ios',
    registrationState: 'available',
    isConnected: false,
    isSending: false,
    didFailToStartSession: false,
    requiresDATAppUpdate: false,
    displayState: 'stopped',
    fallback: {
      reason: 'dat_native_display_unavailable',
      renderPath: 'display-webapp',
      message: 'Native display is not connected. Opening display webapp preview.',
    },
  },
};

export const datUnavailableDisplayState = DAT_DISPLAY_STATES.unavailable;
export const datDisabledDisplayState = DAT_DISPLAY_STATES.disabled;
export const datUnsupportedDisplayState = DAT_DISPLAY_STATES.unsupported;
export const datReadyDisplayState = DAT_DISPLAY_STATES.ready;
export const androidDisplayAccessLifecycleStates = ANDROID_DISPLAY_ACCESS_LIFECYCLE_STATES;
export const iosDisplayFallbackStates = IOS_DISPLAY_FALLBACK_STATES;

export const metaWearablesDisplayStates = {
  dat: DAT_DISPLAY_STATES,
  androidDisplayAccessLifecycle: ANDROID_DISPLAY_ACCESS_LIFECYCLE_STATES,
  iosFallback: IOS_DISPLAY_FALLBACK_STATES,
};

export default metaWearablesDisplayStates;
