const IO_CAPABILITIES_READY = {
  session: true,
  camera: true,
  photoCapture: true,
  videoStream: true,
  audio: true,
  microphoneRoute: true,
  speakerRoute: true,
  headphoneRoute: true,
  display: true,
  displayVideo: true,
  neuralBand: true,
  captouch: true,
  motionOrientation: true,
  phoneGps: true,
};

const MOCK_DEVICE = {
  deviceId: 'mock-meta-glasses-io-001',
  deviceName: 'Meta Glasses Expanded I/O Mock',
  source: 'fixture',
  rssi: -35,
};

export const META_WEARABLES_IO_STATES = {
  ready: {
    id: 'expanded-io-ready',
    available: true,
    platform: 'android',
    sdkLinked: false,
    sdkConfigured: false,
    integrationMode: 'hardware_free_fixture',
    hardwareFree: true,
    credentialsRequired: false,
    datPackageAccessRequired: false,
    pairedGlassesRequired: false,
    physicalHardwareRequired: false,
    capabilities: IO_CAPABILITIES_READY,
    sessionState: 'ready',
    registrationState: 'available',
    selectedDeviceId: MOCK_DEVICE.deviceId,
    selectedDeviceName: MOCK_DEVICE.deviceName,
    activeDeviceId: MOCK_DEVICE.deviceId,
    targetConnectionState: 'ready',
    targetLastSeenAt: 1779440400000,
    targetRssi: MOCK_DEVICE.rssi,
    displayConnectionState: 'ready',
    displayReady: true,
    displayRenderPath: 'native-dat',
    displayLifecycleStages: [
      'target_selected',
      'session_started',
      'display_surface_ready',
      'widget_rendered',
      'widget_updated',
      'widget_cleared',
      'session_stopped',
    ],
    ioRoutes: {
      photoCapture: { readiness: 'ready', surface: 'dat-native' },
      videoStream: { readiness: 'ready', surface: 'dat-native' },
      microphone: { readiness: 'ready', route: 'bluetooth-hfp-input' },
      speaker: { readiness: 'ready', route: 'bluetooth-a2dp-output' },
      headphone: { readiness: 'ready', route: 'bluetooth-a2dp-output' },
      display: { readiness: 'ready', route: 'dat-native-display' },
    },
    events: [
      { eventType: 'io.camera.photo.captured', capability: 'camera.photo_capture' },
      { eventType: 'io.camera.video.ready', capability: 'camera.video_capture' },
      { eventType: 'io.microphone.route.ready', capability: 'microphone.input' },
      { eventType: 'io.speaker.route.ready', capability: 'speaker.output' },
      { eventType: 'io.headphone.route.ready', capability: 'headphone.output' },
      { eventType: 'io.display.lifecycle', capability: 'display.output' },
      { eventType: 'io.neural_band.intent', capability: 'neural_band.input', gesture: 'pinch' },
      { eventType: 'io.captouch.intent', capability: 'captouch.input', touch: 'swipe_forward' },
      { eventType: 'io.motion.orientation', capability: 'motion.orientation', yaw: 12.5, pitch: -2.25, roll: 0.75 },
      { eventType: 'io.phone_gps.context', capability: 'phone_gps.context', latitude: 37.789, longitude: -122.401 },
    ],
    appBindings: [
      'camera.photo_capture.binding',
      'camera.video_capture.binding',
      'microphone.input.binding',
      'speaker.output.binding',
      'headphone.output.binding',
      'display.output.binding',
      'neural_band.input.binding',
      'captouch.input.binding',
      'motion.orientation.binding',
      'phone_gps.context.binding',
    ],
    controlPlaneEnvelopes: [
      { eventType: 'capability.ready', capability: 'camera.photo_capture', correlationId: 'corr-photo-ready' },
      { eventType: 'capability.ready', capability: 'camera.video_capture', correlationId: 'corr-video-ready' },
      { eventType: 'display.lifecycle', capability: 'display.output', correlationId: 'corr-display-lifecycle' },
      { eventType: 'route.recovered', capability: 'microphone.input', correlationId: 'corr-route-recovered' },
    ],
  },
  permissionDenied: {
    id: 'permission-denied',
    readiness: 'permission_denied',
    capability: 'camera.photo_capture',
    requiredAction: 'request_permission_again',
  },
  disconnected: {
    id: 'disconnected',
    readiness: 'disconnected',
    capability: 'display.output',
    targetConnectionState: 'disconnected',
    recovery: 'reconnect_selected_device',
  },
  unsupportedCapability: {
    id: 'unsupported-capability',
    readiness: 'unsupported',
    capability: 'neural_band.input',
    recovery: 'fallback_to_mobile',
  },
  degradedCapability: {
    id: 'degraded-capability',
    readiness: 'degraded',
    capability: 'motion.orientation',
    recovery: 'lower_sample_rate',
  },
  staleSession: {
    id: 'stale-session',
    readiness: 'stale_session',
    capability: 'display.output',
    recovery: 'reset_display_session',
  },
  routeLoss: {
    id: 'route-loss',
    readiness: 'route_lost',
    capability: 'microphone.input',
    recovery: 'reroute_bluetooth_profile',
  },
  recovery: {
    id: 'recovery',
    readiness: 'ready',
    capability: 'microphone.input',
    recovery: 'route_recovered',
  },
};

export function createMetaWearablesIoMockNativeModule(state = META_WEARABLES_IO_STATES.ready) {
  return {
    isAvailable: () => true,
    getConfiguration: async () => ({
      platform: state.platform,
      sdkLinked: state.sdkLinked,
      sdkConfigured: state.sdkConfigured,
      applicationId: 'handsfree-meta-glasses-io-fixture',
    }),
    getCapabilities: async () => state.capabilities,
    getConnectedDevice: async () => MOCK_DEVICE,
    getSessionState: async () => state.sessionState,
    getAdapterState: async () => ({
      transport: 'bluetooth',
      adapterAvailable: true,
      adapterEnabled: true,
      scanPermissionGranted: true,
      connectPermissionGranted: true,
      advertisePermissionGranted: true,
      state: 'powered_on',
    }),
    getKnownDevices: async () => [MOCK_DEVICE],
    scanKnownAndNearbyDevices: async () => [MOCK_DEVICE],
    getSelectedDeviceTarget: async () => MOCK_DEVICE,
    selectDeviceTarget: async () => MOCK_DEVICE,
    clearDeviceTarget: async () => MOCK_DEVICE,
    reconnectSelectedDeviceTarget: async () => ({
      state: 'target_ready',
      mode: 'hardware_free_fixture',
      deviceId: MOCK_DEVICE.deviceId,
      targetConnectionState: 'ready',
      targetRssi: MOCK_DEVICE.rssi,
    }),
    connectSelectedDeviceTarget: async () => ({
      state: 'target_ready',
      mode: 'hardware_free_fixture',
      deviceId: MOCK_DEVICE.deviceId,
      targetConnectionState: 'ready',
      targetRssi: MOCK_DEVICE.rssi,
    }),
    startDeviceSession: async () => ({
      state: 'target_ready',
      mode: 'hardware_free_fixture',
      deviceId: MOCK_DEVICE.deviceId,
      targetConnectionState: 'ready',
    }),
    stopDeviceSession: async () => ({
      state: 'idle',
      mode: 'hardware_free_fixture',
      deviceId: MOCK_DEVICE.deviceId,
      targetConnectionState: 'selected',
    }),
    getDiagnostics: async () => state,
    capturePhoto: async () => ({
      state: 'ready',
      mode: 'hardware_free_fixture',
      supported: true,
      action: 'capture_photo',
      assetUri: 'ipfs://bafybeimockphoto',
      mimeType: 'image/jpeg',
    }),
    startVideoStream: async () => ({
      state: 'ready',
      mode: 'hardware_free_fixture',
      supported: true,
      action: 'start_video_stream',
      streamState: 'ready',
    }),
    stopVideoStream: async () => ({
      state: 'ready',
      mode: 'hardware_free_fixture',
      supported: true,
      action: 'stop_video_stream',
      streamState: 'stopped',
    }),
    addStateListener: () => ({ remove() {} }),
  };
}

export default META_WEARABLES_IO_STATES;
