export const META_WEARABLES_DAT_SOURCE_MATRIX = {
  id: 'mgw-415-public-dat-webapps-source-matrix',
  profile: 'handsfree.meta-glasses/io-source-matrix',
  profileVersion: '0.1.0',
  task: 'MGW-415',
  sourceRefresh: 'MGW-413',
  hardwareFree: true,
  credentialsRequired: false,
  datPackageAccessRequired: false,
  pairedGlassesRequired: false,
  physicalHardwareRequired: false,
  sourceFamilies: [
    'android-dat-displayaccess-v0.7',
    'ios-dat-displayaccess-v0.7',
    'dat-cameraaccess-v0.7',
    'meta-display-webapps-inputs',
    'bluetooth-audio-route-readiness',
  ],
  sourceFamilyDetails: [
    {
      id: 'android-dat-displayaccess-v0.7',
      surface: 'dat-native',
      platform: 'android',
      readiness: 'mocked',
      sampleFamily: 'DisplayAccess',
      evidence: [
        'DeviceSession.addDisplay(config)',
        'DisplayState/DisplayError readiness',
        'Display.sendContent replaces the active view',
        'DAM metadata and release-channel/package gates',
      ],
    },
    {
      id: 'ios-dat-displayaccess-v0.7',
      surface: 'dat-native',
      platform: 'ios',
      readiness: 'mocked',
      sampleFamily: 'DisplayAccess',
      evidence: [
        'DeviceSession.addDisplay',
        'display.send submits FlexBox or VideoPlayer content',
        'Developer Mode, registration, firmware, and glasses-app gates',
        'typed display/video state and error surfaces',
      ],
    },
    {
      id: 'dat-cameraaccess-v0.7',
      surface: 'dat-native',
      platform: 'android-ios',
      readiness: 'mocked',
      sampleFamily: 'CameraAccess',
      evidence: [
        'camera permission simulation',
        'camera session start/stop',
        'camera stream ready/start/stop',
        'photo capture output references',
      ],
    },
    {
      id: 'meta-display-webapps-inputs',
      surface: 'display-webapp',
      platform: 'web',
      readiness: 'mocked',
      sampleFamily: 'Web Apps starter',
      evidence: [
        'Arrow keys and Enter model D-pad activation',
        'Meta Neural Band and captouch normalize to intent events',
        'motion/orientation and phone GPS can be browser tested',
        'local storage is browser-local and quota limited',
      ],
    },
    {
      id: 'bluetooth-audio-route-readiness',
      surface: 'bluetooth-audio',
      platform: 'phone',
      readiness: 'mocked',
      sampleFamily: 'platform audio route',
      evidence: [
        'microphone input readiness is a phone Bluetooth profile route',
        'speaker/headphone output readiness is a phone Bluetooth profile route',
        'route loss and recovery are diagnostics, not DAT audio packets',
      ],
    },
  ],
  fixturePrinciples: [
    'fixtures mirror public lifecycle shapes without importing DAT SDK packages',
    'native DAT owns camera photo/video and display lifecycle mocks',
    'Bluetooth audio is modeled as phone route readiness',
    'Web Apps own Arrow/Enter, Neural Band, captouch, motion/orientation, phone GPS, and local storage mocks',
    'IPFS/libp2p/MCP++ metadata appears only in app-level bridge envelopes',
  ],
  displayAccessLifecycleV07: [
    'sdk_package_checked',
    'release_channel_checked',
    'credentials_checked',
    'developer_mode_checked',
    'app_model_metadata_checked',
    'dam_enabled_checked',
    'display_target_selected',
    'device_session_starting',
    'device_session_started',
    'display_attaching',
    'display_attached',
    'display_state_starting',
    'display_ready',
    'display_content_sent',
    'display_video_player_ready',
    'display_content_replaced',
    'display_session_stopped',
    'display_removed',
  ],
  displaySessionStatesV07: [
    {
      state: 'unavailable',
      readiness: 'package_or_release_channel_unavailable',
      fixtureEvent: 'display.package_unavailable',
      fallback: 'display-webapp',
    },
    {
      state: 'awaiting_update',
      readiness: 'firmware_update_required',
      fixtureEvent: 'display.firmware_update_required',
      fallback: 'mobile-fallback',
    },
    {
      state: 'starting',
      readiness: 'permission_required',
      fixtureEvent: 'display.session_starting',
      fallback: null,
    },
    {
      state: 'started',
      readiness: 'ready',
      fixtureEvent: 'display.session_started',
      fallback: null,
    },
    {
      state: 'content_sent',
      readiness: 'ready',
      fixtureEvent: 'display.content_sent',
      contentShape: 'single_root_flexbox_or_video_player',
    },
    {
      state: 'stopped',
      readiness: 'disconnected',
      fixtureEvent: 'display.session_stopped',
      fallback: 'display-webapp',
    },
  ],
  displayContentSamples: [
    {
      id: 'display-flexbox-widget',
      surface: 'dat-native',
      contentKind: 'FlexBox',
      children: ['Text', 'Image', 'Button'],
      replacementSemantics: 'send_replaces_previous_content',
      viewport: { width: 600, height: 600 },
    },
    {
      id: 'display-video-player',
      surface: 'dat-native',
      contentKind: 'VideoPlayer',
      mediaType: 'video/mp4',
      replacementSemantics: 'send_replaces_previous_content',
    },
  ],
  cameraAccessLifecycleV07: [
    'camera_permission_required',
    'camera_permission_granted',
    'camera_session_starting',
    'camera_session_started',
    'camera_stream_ready',
    'camera_stream_started',
    'camera_photo_requested',
    'camera_photo_captured',
    'camera_stream_backpressure',
    'camera_stream_stopped',
    'camera_session_stopped',
  ],
  cameraStates: [
    {
      id: 'camera-stream-ready',
      capability: 'camera.video_capture',
      state: 'ready',
      readiness: 'ready',
      operation: 'startVideoStream',
      outputRef: {
        cid: 'sha256:mgw415-camera-stream-ready',
        purpose: 'video',
        mediaType: 'video/mp4',
        retentionPolicy: 'ephemeral',
      },
    },
    {
      id: 'camera-photo-captured',
      capability: 'camera.photo_capture',
      state: 'captured',
      readiness: 'ready',
      operation: 'capturePhoto',
      outputRef: {
        cid: 'sha256:mgw415-camera-photo-captured',
        purpose: 'photo',
        mediaType: 'image/jpeg',
        retentionPolicy: 'session',
      },
    },
    {
      id: 'camera-permission-denied',
      capability: 'camera.photo_capture',
      state: 'permission_denied',
      readiness: 'permission_denied',
      operation: 'capturePhoto',
    },
    {
      id: 'camera-stream-backpressure',
      capability: 'camera.video_capture',
      state: 'backpressure',
      readiness: 'degraded',
      operation: 'startVideoStream',
      recovery: 'drop_ephemeral_frames_and_resume',
    },
  ],
  audioRouteStates: [
    {
      capability: 'microphone.input',
      route: 'bluetooth-hfp-input',
      readiness: 'ready',
      profile: 'phone-os-bluetooth',
      fixtureEvent: 'io.microphone.route.ready',
    },
    {
      capability: 'speaker.output',
      route: 'bluetooth-a2dp-output',
      readiness: 'ready',
      profile: 'phone-os-bluetooth',
      fixtureEvent: 'io.speaker.route.ready',
    },
    {
      capability: 'headphone.output',
      route: 'bluetooth-a2dp-output',
      readiness: 'ready',
      profile: 'phone-os-bluetooth',
      fixtureEvent: 'io.headphone.route.ready',
    },
    {
      capability: 'microphone.input',
      route: 'bluetooth-hfp-input',
      readiness: 'route_lost',
      profile: 'phone-os-bluetooth',
      fixtureEvent: 'io.microphone.route.lost',
      recovery: 'reroute_bluetooth_profile',
    },
  ],
  webAppInputs: [
    {
      id: 'webapp-arrow-left',
      key: 'ArrowLeft',
      intent: 'navigate_previous',
      capability: 'captouch.input',
      source: 'browser_keyboard_or_display_dpad',
      normalizedEvent: 'io.captouch.intent',
    },
    {
      id: 'webapp-arrow-right',
      key: 'ArrowRight',
      intent: 'navigate_next',
      capability: 'captouch.input',
      source: 'browser_keyboard_or_display_dpad',
      normalizedEvent: 'io.captouch.intent',
    },
    {
      id: 'webapp-enter',
      key: 'Enter',
      intent: 'activate_selected',
      capability: 'captouch.input',
      source: 'browser_keyboard_or_display_dpad',
      normalizedEvent: 'io.captouch.intent',
    },
    {
      id: 'webapp-neural-band-pinch',
      gesture: 'pinch',
      key: 'Enter',
      intent: 'activate_selected',
      capability: 'neural_band.input',
      source: 'neural_band_or_browser_enter',
      normalizedEvent: 'io.neural_band.intent',
    },
    {
      id: 'webapp-captouch-swipe-forward',
      touch: 'swipe_forward',
      key: 'ArrowRight',
      intent: 'navigate_next',
      capability: 'captouch.input',
      source: 'captouch_or_browser_arrow',
      normalizedEvent: 'io.captouch.intent',
    },
  ],
  sensorContexts: [
    {
      id: 'motion-orientation',
      capability: 'motion.orientation',
      surface: 'display-webapp',
      sample: {
        yaw: 12.5,
        pitch: -2.25,
        roll: 0.75,
        quaternion: [0.99, 0.02, -0.04, 0.1],
        source: 'browser-devtools-orientation-mock',
      },
    },
    {
      id: 'phone-gps',
      capability: 'phone_gps.context',
      surface: 'display-webapp',
      sample: {
        source: 'phone-os-mock',
        latitude: 37.789,
        longitude: -122.401,
        accuracyM: 8,
      },
    },
  ],
  storageLimits: [
    {
      id: 'webapp-local-storage-quota',
      surface: 'display-webapp',
      capability: 'display.output',
      limit: 'browser_local_storage_quota',
      durability: 'browser_local_not_control_plane',
      readiness: 'degraded',
      recovery: 'drop_ephemeral_frames_and_resume',
    },
  ],
  failureModes: [
    {
      id: 'permission_denial',
      capability: 'camera.photo_capture',
      readiness: 'permission_denied',
      sourceFamily: 'dat-cameraaccess-v0.7',
      recovery: 'request_permission_again',
    },
    {
      id: 'unsupported_display',
      capability: 'display.output',
      readiness: 'unsupported',
      sourceFamily: 'android-dat-displayaccess-v0.7',
      recovery: 'fallback_to_display_webapp_or_mobile',
    },
    {
      id: 'release_channel_missing',
      capability: 'display.output',
      readiness: 'package_or_release_channel_unavailable',
      sourceFamily: 'android-dat-displayaccess-v0.7',
      recovery: 'fallback_to_display_webapp_or_mobile',
    },
    {
      id: 'firmware_update_required',
      capability: 'display.output',
      readiness: 'firmware_update_required',
      sourceFamily: 'ios-dat-displayaccess-v0.7',
      recovery: 'show_update_required_receipt',
    },
    {
      id: 'dat_app_update_required',
      capability: 'display.output',
      readiness: 'dat_app_update_required',
      sourceFamily: 'ios-dat-displayaccess-v0.7',
      recovery: 'show_update_required_receipt',
    },
    {
      id: 'route_loss',
      capability: 'microphone.input',
      readiness: 'route_lost',
      sourceFamily: 'bluetooth-audio-route-readiness',
      recovery: 'reroute_bluetooth_profile',
    },
    {
      id: 'backpressure',
      capability: 'camera.video_capture',
      readiness: 'degraded',
      sourceFamily: 'dat-cameraaccess-v0.7',
      recovery: 'drop_ephemeral_frames_and_resume',
    },
    {
      id: 'local_storage_limit',
      capability: 'display.output',
      readiness: 'degraded',
      sourceFamily: 'meta-display-webapps-inputs',
      recovery: 'drop_ephemeral_frames_and_resume',
    },
    {
      id: 'recovery',
      capability: 'microphone.input',
      readiness: 'ready',
      sourceFamily: 'bluetooth-audio-route-readiness',
      recovery: 'route_recovered',
    },
  ],
  bridgeEnvelopes: [
    {
      id: 'camera-photo-captured-envelope',
      eventType: 'capability.ready',
      capability: 'camera.photo_capture',
      surface: 'dat-native',
      correlationId: 'mgw415-photo-ready',
      payloadRefs: ['sha256:mgw415-camera-photo-captured'],
      receipt: {
        receiptKind: 'mcp++/capability-readiness',
        receiptCid: 'sha256:mgw415-photo-ready-receipt',
      },
    },
    {
      id: 'display-lifecycle-envelope',
      eventType: 'display.lifecycle',
      capability: 'display.output',
      surface: 'dat-native',
      correlationId: 'mgw415-display-lifecycle',
      payloadRefs: ['sha256:mgw415-display-content'],
      receipt: {
        receiptKind: 'mcp++/control-route',
        receiptCid: 'sha256:mgw415-display-lifecycle-receipt',
      },
    },
    {
      id: 'route-recovered-envelope',
      eventType: 'route.recovered',
      capability: 'microphone.input',
      surface: 'bluetooth-audio',
      correlationId: 'mgw415-route-recovered',
      payloadRefs: ['sha256:mgw415-route-recovered'],
      receipt: {
        receiptKind: 'mcp++/capability-readiness',
        receiptCid: 'sha256:mgw415-route-recovered-receipt',
      },
    },
  ],
};

export function createMetaWearablesDatSourceMatrixMock() {
  return {
    ...META_WEARABLES_DAT_SOURCE_MATRIX,
    scenarios: {
      displayReady: META_WEARABLES_DAT_SOURCE_MATRIX.displayAccessLifecycleV07,
      displaySessionStates: META_WEARABLES_DAT_SOURCE_MATRIX.displaySessionStatesV07,
      cameraReady: META_WEARABLES_DAT_SOURCE_MATRIX.cameraAccessLifecycleV07,
      cameraStates: META_WEARABLES_DAT_SOURCE_MATRIX.cameraStates,
      webAppInputs: META_WEARABLES_DAT_SOURCE_MATRIX.webAppInputs,
      audioRoutes: META_WEARABLES_DAT_SOURCE_MATRIX.audioRouteStates,
      storageLimits: META_WEARABLES_DAT_SOURCE_MATRIX.storageLimits,
      failureModes: META_WEARABLES_DAT_SOURCE_MATRIX.failureModes,
      bridgeEnvelopes: META_WEARABLES_DAT_SOURCE_MATRIX.bridgeEnvelopes,
    },
  };
}

export default META_WEARABLES_DAT_SOURCE_MATRIX;
