#!/usr/bin/env python3
"""
Script to create draft PRs for remaining implementation gaps.
Generated by GitHub Copilot assistant.

Requirements:
    - gh CLI installed and authenticated
    - Git repository with tracking documents
"""

import subprocess
import sys
import os
from pathlib import Path

REPO = "endomorphosis/lift_coding"
BASE_BRANCH = "main"

# PR definitions
PRS_TO_CREATE = [
    {
        "number": "026-notification-push-delivery",
        "title": "PR-026: Automatic push notification delivery",
        "tracking": "tracking/PR-026-notification-push-delivery.md",
    },
    {
        "number": "027-profile-verbosity-tuning",
        "title": "PR-027: Profile-based summary verbosity tuning",
        "tracking": "tracking/PR-027-profile-verbosity-tuning.md",
    },
    {
        "number": "028-external-agent-runner-setup",
        "title": "PR-028: External agent runner setup guide",
        "tracking": "tracking/PR-028-external-agent-runner-setup.md",
    },
]


def run_command(cmd, check=True, capture=True):
    """Run a shell command and return the result."""
    try:
        result = subprocess.run(
            cmd,
            shell=True,
            check=check,
            capture_output=capture,
            text=True,
        )
        return result.stdout.strip() if capture else None
    except subprocess.CalledProcessError as e:
        if capture:
            print(f"Error running command: {cmd}")
            print(f"  stdout: {e.stdout}")
            print(f"  stderr: {e.stderr}")
        raise


def check_prerequisites():
    """Check if required tools are available."""
    print("Checking prerequisites...")
    
    # Check gh CLI
    try:
        run_command("gh --version")
        print("✓ gh CLI is installed")
    except (subprocess.CalledProcessError, FileNotFoundError):
        print("✗ Error: gh CLI is not installed")
        print("  Install from: https://cli.github.com/manual/installation")
        return False
    
    # Check gh auth
    try:
        run_command("gh auth status")
        print("✓ gh CLI is authenticated")
    except subprocess.CalledProcessError:
        print("✗ Error: Not authenticated with GitHub")
        print("  Run: gh auth login")
        return False
    
    print("")
    return True


def create_draft_pr(pr_info):
    """Create a draft PR for the given PR info."""
    pr_number = pr_info["number"]
    title = pr_info["title"]
    tracking_file = pr_info["tracking"]
    branch_name = f"draft/pr-{pr_number}"
    
    print(f"Creating {title}")
    print(f"  Branch: {branch_name}")
    print(f"  Tracking: {tracking_file}")
    
    # Check if tracking file exists
    if not Path(tracking_file).exists():
        print(f"  ✗ Error: Tracking file not found: {tracking_file}")
        return False
    
    # Create and switch to branch
    try:
        run_command(f"git checkout -b {branch_name} {BASE_BRANCH}", check=False)
    except subprocess.CalledProcessError:
        # Branch might exist, try to check it out
        run_command(f"git checkout {branch_name}")
    
    # Create initial plan file
    plan_file = f"work/pr-{pr_number}-plan.md"
    plan_content = f"""# {title}

## Status
Ready for implementation by GitHub Copilot agent.

## Tracking Document
See `{tracking_file}` for full details.

## Implementation
This PR will be implemented by a GitHub Copilot agent according to the specifications in the tracking document.

Refer to the tracking document for:
- Full problem statement and context
- Implementation scope and approach
- Acceptance criteria
- Related files and PRs
"""
    
    Path(plan_file).write_text(plan_content)
    
    # Commit the plan
    run_command(f"git add {plan_file}")
    commit_msg = f"PR-{pr_number}: Initial plan\n\nReady for GitHub Copilot agent implementation. See {tracking_file} for details."
    run_command(f'git commit -m "{commit_msg}"')
    
    # Push the branch
    print("  Pushing branch...")
    run_command(f"git push -u origin {branch_name}")
    
    # Create the draft PR
    print("  Creating draft PR...")
    try:
        pr_url = run_command(
            f'gh pr create --repo {REPO} --base {BASE_BRANCH} --head {branch_name} '
            f'--title "{title}" --body-file {tracking_file} --draft --label copilot-agent'
        )
        
        # Extract URL from output
        for line in pr_url.split('\n'):
            if 'github.com' in line:
                print(f"  ✓ Created: {line}")
                print("")
                return True
        
        print(f"  ✓ Draft PR created")
        print("")
        return True
    except subprocess.CalledProcessError:
        print("  ✗ Failed to create PR")
        print("")
        return False


def main():
    """Main function to create all draft PRs."""
    print("Creating draft PRs for remaining implementation gaps...")
    print(f"Repository: {REPO}")
    print(f"Base branch: {BASE_BRANCH}")
    print("")
    
    # Check prerequisites
    if not check_prerequisites():
        return 1
    
    # Return to base branch
    print(f"Checking out {BASE_BRANCH}...")
    run_command(f"git checkout {BASE_BRANCH}")
    run_command(f"git pull origin {BASE_BRANCH}")
    print("")
    
    # Create each PR
    success_count = 0
    for pr_info in PRS_TO_CREATE:
        if create_draft_pr(pr_info):
            success_count += 1
        
        # Return to base branch for next PR
        run_command(f"git checkout {BASE_BRANCH}")
    
    print("")
    print(f"✓ Created {success_count}/{len(PRS_TO_CREATE)} draft PRs successfully!")
    print("")
    print("Next steps:")
    print("  1. Review the created PRs on GitHub")
    print("  2. Assign them to GitHub Copilot agents")
    print("  3. Copilot agents will implement according to tracking docs")
    
    return 0 if success_count == len(PRS_TO_CREATE) else 1


if __name__ == "__main__":
    sys.exit(main())
