#!/bin/bash
# Script to create draft PRs for remaining implementation gaps
# Generated by GitHub Copilot assistant

set -e

REPO="endomorphosis/lift_coding"
BASE_BRANCH="main"

echo "Creating draft PRs for remaining implementation gaps..."
echo "Repository: $REPO"
echo "Base branch: $BASE_BRANCH"
echo ""

# Check if gh CLI is available and authenticated
if ! command -v gh &> /dev/null; then
    echo "Error: gh CLI is not installed. Please install it first:"
    echo "  https://cli.github.com/manual/installation"
    exit 1
fi

if ! gh auth status &> /dev/null; then
    echo "Error: Not authenticated with GitHub. Please run 'gh auth login' first."
    exit 1
fi

echo "✓ GitHub CLI is available and authenticated"
echo ""

# Function to create a draft PR
create_draft_pr() {
    local pr_number=$1
    local pr_suffix=$2
    local title=$3
    local branch_name="draft/pr-${pr_number}-${pr_suffix}"
    local tracking_file="tracking/PR-${pr_number}-${pr_suffix}.md"
    
    echo "Creating PR-${pr_number}: ${title}"
    echo "  Branch: ${branch_name}"
    echo "  Tracking: ${tracking_file}"
    
    # Check if tracking file exists
    if [ ! -f "$tracking_file" ]; then
        echo "  ✗ Error: Tracking file not found: ${tracking_file}"
        return 1
    fi
    
    # Create and switch to branch
    git checkout -b "$branch_name" "$BASE_BRANCH" 2>/dev/null || git checkout "$branch_name"
    
    # Create initial plan file
    local plan_file="work/pr-${pr_number}-plan.md"
    cat > "$plan_file" <<EOF
# ${title}

## Status
Ready for implementation by GitHub Copilot agent.

## Tracking Document
See \`${tracking_file}\` for full details.

## Implementation
This PR will be implemented by a GitHub Copilot agent according to the specifications in the tracking document.

Refer to the tracking document for:
- Full problem statement and context
- Implementation scope and approach
- Acceptance criteria
- Related files and PRs
EOF
    
    # Commit the plan
    git add "$plan_file"
    git commit -m "PR-${pr_number}: Initial plan" -m "Ready for GitHub Copilot agent implementation. See ${tracking_file} for details."
    
    # Push the branch
    echo "  Pushing branch..."
    git push -u origin "$branch_name"
    
    # Create the draft PR
    echo "  Creating draft PR..."
    local pr_url=$(gh pr create \
        --repo "$REPO" \
        --base "$BASE_BRANCH" \
        --head "$branch_name" \
        --title "$title" \
        --body-file "$tracking_file" \
        --draft \
        --label "copilot-agent" \
        --json url --jq .url)
    
    local exit_code=$?
    
    if [ $exit_code -eq 0 ] && [ -n "$pr_url" ]; then
        echo "  ✓ Created: $pr_url"
        echo ""
        return 0
    else
        echo "  ✗ Failed to create PR"
        echo ""
        return 1
    fi
}

# Return to main branch to start clean
git checkout "$BASE_BRANCH"
git pull origin "$BASE_BRANCH"

# Create PR-026: Automatic push notification delivery
create_draft_pr "026" "notification-push-delivery" "PR-026: Automatic push notification delivery"

# Create PR-027: Profile-based summary verbosity tuning
create_draft_pr "027" "profile-verbosity-tuning" "PR-027: Profile-based summary verbosity tuning"

# Create PR-028: External agent runner setup
create_draft_pr "028" "external-agent-runner-setup" "PR-028: External agent runner setup guide"

# Return to main branch
git checkout "$BASE_BRANCH"

echo ""
echo "✓ All draft PRs created successfully!"
echo ""
echo "Next steps:"
echo "  1. Review the created PRs on GitHub"
echo "  2. Assign them to GitHub Copilot agents"
echo "  3. Copilot agents will implement according to tracking docs"
